In [2]:
import pandas as pd
import numpy as np

In [ ]:
df_a = pd.read_csv('dataset.csv',encoding='mbcs',header=None)   
df_b = pd.read_csv('header.csv',sep=";",encoding='mbcs',header=None)   
df_c = pd.concat([df_b, df_a], axis=0)

C:\Users\GONCA\AppData\Local\Temp\ipykernel_8756\1538530644.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_a = pd.read_csv('dataset.csv',encoding='mbcs',header=None)

In [6]:
df_c

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,iscteid;referencia;cpostaldestino;cliente;loca...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2,NaN,8005-420,88888882.0,FARO,0.0,HUB,20250302.0,235644.0,NaN,NaN,0.0,0.0,0.0
1,3,29860138252642,8135-182,88888882.0,ALMANCIL,0.0,HUB,20250302.0,235657.0,NaN,NaN,0.0,0.0,0.0
2,4,NaN,8500-510,88888882.0,PORTIMAO,0.0,HUB,20250302.0,235651.0,NaN,NaN,0.0,0.0,0.0
3,5,29860138237939,8500-513,88888882.0,PORTIMAO,0.0,HUB,20250302.0,235658.0,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1132307,188436,PRZ/65761326,30100,3182817.0,ALES,0.0,HUB,20250304.0,235253.0,NaN,NaN,0.0,0.0,0.0
1132308,173076,PRZ/65764524,30900,3182817.0,NIMES,0.0,HUB,20250304.0,235414.0,NaN,NaN,0.0,0.0,0.0
1132309,303227,PRZ/65792184,94300,3182817.0,VINCENNES,0.0,HUB,20250304.0,235313.0,NaN,NaN,0.0,0.0,0.0
1132310,160703,PRZ/65727492,13090,3182817.0,AIX EN PROVENCE,0.0,HUB,20250304.0,235415.0,NaN,NaN,0.0,0.0,0.0
1132311,132864,F003250005906,52000,3030005.0,CHAUMONT,2.1,HUB,20250304.0,235402.0,NaN,NaN,0.0,0.0,0.0